# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6decfab275e67600e0adb9a52773e5af46d6fadad219fd3601569bb2045210dc5b5da6de5a3077e1d2e9df12a505b8252fb62b420cda2e453d777dad88df353f

test:
  secret_key_base: 4b56471274f62000102a5c6e39ed35ead41d74a44e3c6d434988c706720f61b65764c53bf47215e00297f0ee8d8474fb0d9dff8dd44b73b79c826db1e9a3f46b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
